import sys

def intro():
    print("== Introduction to Beans ==")
    print("Beans is a replacement for Markdown. It is a simple, easy to use, and powerful tool for creating README files.")
    print("Beans includes many tools, such as:")
    print("\n")
    print("header - Create a header with text")
    print("print - Add text to that header")
    print("console - Log text to the console")
    print("beans init - Start a beans program")
    print("beans create - Create a new file")
    print("breakline - Add a line break")
    print("\n")
    print("Tool usage:")
    print("\n")
    print("\n")
    print("\n")
    print("The header tool is used to create a header.")
    print("Headers will be displayed like this: ")
    print("\n")
    print(".beans - header name")
    print(".txt - == name ==")
    print(".md - # name")
    print("\n\n\n")
    print("The print tool is used to add text to the header.")
    print("This can be anything from a line of text to a full paragraph.")
    print("\n")
    print(".beans - print text")
    print(".beans - print This is a bunch of text")
    print(".txt - text")
    print(".txt - This is a bunch of text.")
    print(".md - text")
    print(".md - This is a bunch of text.")
    print("\n\n\n")
    print("The console tool is used to log text to the console.")
    print("This is mostly used for debugging.")
    print("\n\n\n")
    print("The beans init tool is used to start a beans program.")
    print("This is only used for .beans files. It will be removed when you compile them down.")
    print("\n\n\n")
    print("The beans create tool is used to create a new file.")
    print("This is only used for .beans files. It will be removed when you compile them down.")
    print("\n\n\n")
    print("The breakline tool is used to add a line break.")
    print("This can be used to add lines, you can have as many of these as you want.")
    print("\n\n\n")
    print("\n\n\n")
    print("There are different types of files that Beans can create and read.")
    print("\n\n\n")
    print("1. .beans")
    print("The .beans file is used with Default beans projects, and can be included with any project.")
    print("THe .beans file can also include print commands.")
    print("\n")
    print("2. .txt")
    print("The .txt file is used for text files, and is not read by Beans, only written.")
    print("This is a type of file that Beans can compile to.")
    print("\n")
    print("3. .md")
    print("The .md file is used for Markdown files, and can be used with Github and other tools.")
    print("This is a type of file that Beans can compile to.")
    print("\n\n\n")
    print("Good Luck using Beans!")
